<footer class="footer">
	<div class="container">
		<p>Team 8 Website- Yukako Ito, Annie Zhang, Carolyn Zelicof, Rebeeca Van Dyke, and Jie Deng</p>
		<p>Redesign by Team 9- Miranda Lakis, Meichuanzi Shi, Lerong Wang, Tiffany White, and Luka Sherman.  </p>
	</div>
</footer>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="js/bootstrap.min.js"></script>