	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/styles.css" rel="stylesheet">
	<link href="css/slideshow.css" rel="stylesheet">
	<link rel="stylesheet" href="sss/sss.css">
	<link href="https://fonts.googleapis.com/css?family=Graduate|Raleway|Source+Sans+Pro" rel="stylesheet">
</head>

<body>
	<div class="container">